package us.ihmc.atlas.StepAdjustmentVisualizers;

public enum PushDirection
{
   FORWARD_IN_45, FORWARD_IN_30, FORWARD, FORWARD_30, FORWARD_45, FORWARD_60, OUTWARD, BACKWARD_60, BACKWARD_45, BACKWARD_30, BACKWARD, BACKWARD_IN_30, BACKWARD_IN_45, INWARD
}
