package us.ihmc.atlas.StepAdjustmentVisualizers;

public enum TestType
{
   BIG_ADJUSTMENT, SPEED_UP_ONLY, FEEDBACK_ONLY, ADJUSTMENT_ONLY, FEEDBACK_WITH_ANGULAR,
   ADJUSTMENT_WITH_ANGULAR, SPEED_UP_ADJUSTMENT_WITH_ANGULAR, TIMING, TIMING_WITH_ANGULAR
}
